local M = {}

M.autobackslash = {
    { context = { trig = "pi", name = "pi" },         command = [[\pi]] },
    { context = { trig = "chi", name = "chi" },       command = [[\chi]] },
    { context = { trig = "phi", name = "phi" },       command = [[\phi]] },
    { context = { trig = "Phi", name = "Phi" },       command = [[\Phi]] },
    { context = { trig = "Psi", name = "Psi" },       command = [[\Psi]] },
    { context = { trig = "psi", name = "psi" },       command = [[\psi]] },
    { context = { trig = "nu", name = "nu" },         command = [[\nu]] },
    { context = { trig = "xi", name = "xi" },         command = [[\xi]] },
    { context = { trig = "Xi", name = "Xi" },         command = [[\Xi]] },
    { context = { trig = "mu", name = "mu" },         command = [[\mu]] },
    { context = { trig = "cap", name = "cap" },       command = [[\cap]] },
    { context = { trig = "cup", name = "cup" },       command = [[\cup]] },
    { context = { trig = "neq", name = "neq" },       command = [[\neq]] },
    { context = { trig = "lim", name = "lim" },       command = [[\lim]] },
    { context = { trig = "leq", name = "leq" },       command = [[\leq]] },
    { context = { trig = "geq", name = "geq" },       command = [[\geq]] },
    { context = { trig = "sum", name = "sum" },       command = [[\sum]] },
    { context = { trig = "prod", name = "prod" },     command = [[\prod]] },
    { context = { trig = "int", name = "int" },       command = [[\int]] },
    { context = { trig = "dif", name = "dif" },       command = [[\dif]] },
    { context = { trig = "notin", name = "notin" },   command = [[\notin]] },
    { context = { trig = "to", name = "to" },         command = [[\to]] },
    { context = { trig = "mid", name = "mid" },       command = [[\mid]] },
    { context = { trig = "iff", name = "iff" },       command = [[\iff]] },
    { context = { trig = "quad", name = "quad" },     command = [[\quad]] },
    { context = { trig = "arcsin", name = "arcsin" }, command = [[\arcsin]] },
    { context = { trig = "sin", name = "sin" },       command = [[\sin]] },
    { context = { trig = "arccos", name = "arccos" }, command = [[\arccos]] },
    { context = { trig = "cos", name = "cos" },       command = [[\cos]] },
    { context = { trig = "arctan", name = "arctan" }, command = [[\arctan]] },
    { context = { trig = "tan", name = "tan" },       command = [[\tan]] },
    { context = { trig = "cot", name = "cot" },       command = [[\cot]] },
    { context = { trig = "csc", name = "csc" },       command = [[\csc]] },
    { context = { trig = "sec", name = "sec" },       command = [[\sec]] },
    { context = { trig = "log", name = "log" },       command = [[\log]] },
    { context = { trig = "ln", name = "ln" },         command = [[\ln]] },
    { context = { trig = "exp", name = "exp" },       command = [[\exp]] },
    { context = { trig = "ast", name = "ast" },       command = [[\ast]] },
    { context = { trig = "star", name = "star" },     command = [[\star]] },
    { context = { trig = "perp", name = "perp" },     command = [[\perp]] },
    { context = { trig = "inf", name = "inf" },       command = [[\inf]] },
    { context = { trig = "det", name = "det" },       command = [[\det]] },
    { context = { trig = "max", name = "max" },       command = [[\max]] },
    { context = { trig = "min", name = "min" },       command = [[\min]] },
    { context = { trig = "argmax", name = "argmax" }, command = [[\argmax]] },
    { context = { trig = "argmin", name = "argmin" }, command = [[\argmin]] },
    { context = { trig = "deg", name = "deg" },       command = [[\deg]] },
    { context = { trig = "angle", name = "angle" },   command = [[\angle]] },
}

M.imap = {
    { context = { trig = '`a', name = "alpha", },                           command = [[\alpha]] },
    { context = { trig = '`b', name = "beta", },                            command = [[\beta]] },
    { context = { trig = '`c', name = "chi", },                             command = [[\chi]] },
    { context = { trig = '`d', name = "delta", },                           command = [[\delta]] },
    { context = { trig = '`e', name = "epsilon", },                         command = [[\epsilon]] },
    { context = { trig = '`g', name = "gamma", },                           command = [[\gamma]] },
    { context = { trig = '`h', name = "eta", },                             command = [[\eta]] },
    { context = { trig = '`i', name = "iota", },                            command = [[\iota]] },
    { context = { trig = '`k', name = "kappa", },                           command = [[\kappa]] },
    { context = { trig = '`l', name = "lambda", },                          command = [[\lambda]] },
    { context = { trig = '`n', name = "nabla", },                           command = [[\nabla]] },
    { context = { trig = '`p', name = "partial", },                         command = [[\partial]] },
    { context = { trig = '`q', name = "theta", },                           command = [[\theta]] },
    { context = { trig = '`r', name = "rho", },                             command = [[\rho]], },
    { context = { trig = '`s', name = "sigma", },                           command = [[\sigma]] },
    { context = { trig = '`t', name = "tau", },                             command = [[\tau]], },
    { context = { trig = '`u', name = "upsilon", },                         command = [[\upsilon]] },
    { context = { trig = '`w', name = "omega", },                           command = [[\omega]] },
    { context = { trig = '`z', name = "zeta", },                            command = [[\zeta]] },
    { context = { trig = '`D', name = "Delta", },                           command = [[\Delta]] },
    { context = { trig = '`G', name = "Gamma", },                           command = [[\Gamma]] },
    { context = { trig = '`L', name = "Lambda", },                          command = [[\Lambda]] },
    { context = { trig = '`W', name = "Omega", },                           command = [[\Omega]] },
    { context = { trig = '`\\', name = "setminus", trigEngine = "plain" },  command = [[\setminus]] },
    { context = { trig = '`0', name = "varnothing", trigEngine = "plain" }, command = [[\varnothing]] },
    { context = { trig = '`8', name = "infty", trigEngine = "plain" },      command = [[\infty]] },
    { context = { trig = '`.', name = "cdot", trigEngine = "plain" },       command = [[\cdot]] },
    -- { context = { trig = '`(', name = "subset", trigEngine = "plain" },     command = [[\subseteq]] },
    { context = { trig = '`)', name = "supset", trigEngine = "plain" },     command = [[\supseteq]] },
    { context = { trig = '`[', name = "subseteq", trigEngine = "plain" },   command = [[\subseteq]] },
    { context = { trig = '`]', name = "supseteq", trigEngine = "plain" },   command = [[\supseteq]] },
    { context = { trig = '`=', name = "equiv", trigEngine = "plain" },      command = [[\equiv]] },
}

M.symbol = {
    { context = { trig = 'vep', name = "ε" }, command = [[\varepsilon]] },
    { context = { trig = 'vph', name = "φ" }, command = [[\varphi]] },
    { context = { trig = 'inn', name = "∈" }, command = [[\in]] },
    { context = { trig = 'oo', name = "○" }, command = [[\circ]] },
    { context = { trig = 'OO', name = "⊕" }, command = [[\oplus]] },
    { context = { trig = 'xx', name = "×" }, command = [[\times]] },
    { context = { trig = 'XX', name = "⊗" }, command = [[\otimes]] },
    { context = { trig = 'NN', name = "ℕ" }, command = [[\mathbb{N}]] },
    { context = { trig = 'ZZ', name = "ℤ" }, command = [[\mathbb{Z}]] },
    { context = { trig = 'QQ', name = "ℚ" }, command = [[\mathbb{Q}]] },
    { context = { trig = 'RR', name = "ℝ" }, command = [[\mathbb{R}]] },
    { context = { trig = 'CC', name = "ℂ" }, command = [[\mathbb{C}]] },
    { context = { trig = 'AA', name = "∀" }, command = [[\forall]] },
    { context = { trig = 'EE', name = "∃" }, command = [[\exists]] },
    { context = { trig = 'bcap', name = "∩" }, command = [[\bigcap]] },
    { context = { trig = 'bcup', name = "∪" }, command = [[\bigcup]] },
    { context = { trig = "+-", name = "±", trigEngine = "plain" }, command = [[\pm]] },
    { context = { trig = "-+", name = "∓", trigEngine = "plain" }, command = [[\mp]] },
    { context = { trig = "~-", name = "≃", trigEngine = "plain" }, command = [[\simeq]] },
    { context = { trig = "=>", name = "⇒", trigEngine = "plain" }, command = [[\implies]] },
    { context = { trig = "<=", name = "⇐", trigEngine = "plain" }, command = [[\impliedby]] },
    { context = { trig = "!>", name = "→", trigEngine = "plain" }, command = [[\mapsto]] },
}

M.postfixmath = {
    { context = { trig = "vec", name = "vector", dscr = "vector", },                                        command = [[\vec]] },
    { context = { trig = "dtt", name = "dot", dscr = "dot", },                                              command = [[\dot]] },
    { context = { trig = "bar", name = "bar", dscr = "bar (overline)", },                                   command = [[\overline]] },
    { context = { trig = "tld", name = "tilde", dscr = "tilde (widetilde)", },                              command = [[\widetilde]] },
    { context = { trig = "hat", name = "hat", dscr = "hat (widehat)", },                                    command = [[\widehat]] },
    { context = { trig = "mbb", name = "mathbb", dscr = "math blackboard bold" },                           command = [[\mathbb]] },
    { context = { trig = "mbf", name = "mathbf", dscr = "math bold" },                                      command = [[\mathbf]] },
    { context = { trig = "mcl", name = "mathcal", dscr = "math calligraphic" },                             command = [[\mathcal]] },
    { context = { trig = "msc", name = "mathscr", dscr = "math script", },                                  command = [[\mathscr]] },
    { context = { trig = "mfk", name = "mathfrak", dscr = "mathfrak", },                                    command = [[\mathfrak]], },
    { context = { trig = "opn", name = "operatorname", dscr = "operatorname", match_pattern = [[[%a]*$]] }, command = [[\operatorname]] },
    { context = { trig = "mod", name = "modulo", dscr = "modulo", },                                        command = [[\mod]] },
    { context = { trig = "pmod", name = "modulo with bracket", dscr = "modulo with bracket", },             command = [[\pmod]] }
}

return M
